global_costmap:
  global_frame: map
  robot_base_frame: dummy
  update_frequency: 1.0 # 10.0
  publish_frequency: 1.0 #10.0
  transform_tolerance: 1.0 #0.75 #0.5
  # footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
  robot_radius: 0.35
  inflation_radius: 0.36
  cost_scaling_factor: 50.0
  static_map: true
